import type { Metadata } from "next";
import { Bullets, LegalPage, Section } from "@/components/LegalPage";
import { COMPANY } from "@/lib/company";

/**
 * ⚠️ TEMPLATE — REQUIRES LEGAL REVIEW BEFORE PUBLICATION.
 * Not legal advice. Have counsel review this and fill in every placeholder in
 * src/lib/company.ts (entity name, address, governing jurisdiction) first.
 */
export const metadata: Metadata = {
  title: "Terms & Conditions",
  description:
    "The terms governing your use of SoakinGarri products and services.",
};

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms & Conditions"
      intro={`These terms govern your use of ${COMPANY.name}'s websites and products. By creating an account or using our services, you agree to them.`}
    >
      <Section n={1} title="Who we are">
        <p>
          The services are operated by {COMPANY.legalName}, registered at{" "}
          {COMPANY.address} ({COMPANY.registrationNumber}). &quot;We&quot;,
          &quot;us&quot;, and &quot;{COMPANY.name}&quot; refer to that entity.
        </p>
      </Section>

      <Section n={2} title="Your account">
        <p>
          You need an account to use most of our products. You are responsible
          for keeping your credentials secure and for activity under your
          account. Give us accurate information, and tell us promptly at{" "}
          <a href={`mailto:${COMPANY.email.support}`} className="text-brand-300 hover:underline">
            {COMPANY.email.support}
          </a>{" "}
          if you believe your account has been compromised. One account is for
          one person; don&apos;t share it.
        </p>
      </Section>

      <Section n={3} title="Acceptable use">
        <p>You agree not to:</p>
        <Bullets
          items={[
            "Use the services for anything unlawful, or to harm, harass, defraud, or impersonate anyone.",
            "Attempt to breach, probe, or disrupt our systems, or circumvent rate limits and access controls.",
            "Scrape, resell, or redistribute our output as a competing service.",
            "Submit content you have no right to submit, or that infringes someone else's rights.",
            "Use our cultural tools to produce demeaning, stereotyping, or hateful depictions of any group.",
            "Present AI-generated output as professionally certified engineering, legal, medical, or financial advice.",
          ]}
        />
        <p>
          We may suspend or terminate accounts that breach these terms, and will
          tell you why where we lawfully can.
        </p>
      </Section>

      <Section n={4} title="Your content and ours">
        <p>
          You keep ownership of what you submit. You grant us a limited licence
          to host, process, and transmit it strictly to operate the service for
          you. As between you and us, you own the output generated for you from
          your inputs, to the extent such rights exist and subject to these
          terms.
        </p>
        <p>
          We keep ownership of our software, brand, and content. Nothing here
          transfers our intellectual property to you. Output is generated by
          models and may not be unique — similar output may be produced for
          others.
        </p>
      </Section>

      <Section n={5} title="AI output — accuracy and limits">
        <p>
          Our products generate output using AI models. That output can be
          incomplete, out of date, or plainly wrong. It is provided for
          information and study, and you are responsible for verifying anything
          you rely on. In particular:
        </p>
        <Bullets
          items={[
            "Educational output is study support, not a guarantee of any exam result, and is not a substitute for your syllabus or teacher.",
            "Historical and cultural output should be checked against the cited sources and other scholarship.",
            "Mechanical part dimensions are estimates. They require physical measurement and validation before machining, manufacture, or any G-code generation. Do not cut material on our numbers alone.",
            "Factory plans, costs, and machinery recommendations are indicative modelling, not professional engineering, investment, or regulatory advice. Commission qualified professionals before committing capital.",
          ]}
        />
      </Section>

      <Section n={6} title="Availability">
        <p>
          We work to keep the services running but do not promise uninterrupted
          availability. We may change, suspend, or discontinue any part of a
          product, and will give reasonable notice of material changes where we
          can.
        </p>
      </Section>

      <Section n={7} title="Fees">
        <p>
          Where a product or tier carries a fee, we will tell you the price and
          terms before you commit. Any changes to fees apply prospectively and we
          will notify you in advance.
        </p>
      </Section>

      <Section n={8} title="Disclaimers">
        <p>
          To the fullest extent permitted by law, the services are provided
          &quot;as is&quot; and &quot;as available&quot;, without warranties of
          any kind — express or implied — including merchantability, fitness for
          a particular purpose, non-infringement, and accuracy of output.
        </p>
      </Section>

      <Section n={9} title="Liability">
        <p>
          To the fullest extent permitted by law, we are not liable for indirect,
          incidental, special, consequential, or punitive damages, nor for lost
          profits, revenue, data, or goodwill, arising from your use of the
          services. Nothing in these terms excludes liability that cannot lawfully
          be excluded — including for death or personal injury caused by
          negligence, or for fraud.
        </p>
      </Section>

      <Section n={10} title="Indemnity">
        <p>
          You agree to indemnify us against claims, losses, and reasonable costs
          arising from your breach of these terms, your content, or your unlawful
          use of the services.
        </p>
      </Section>

      <Section n={11} title="Termination">
        <p>
          You may stop using the services and close your account at any time. We
          may suspend or terminate access if you materially breach these terms,
          or if we are required to by law. Provisions that by their nature should
          survive termination will do so.
        </p>
      </Section>

      <Section n={12} title="Changes to these terms">
        <p>
          We may update these terms as our products evolve. We will post the
          revised version here with a new revision date, and give notice of
          material changes. Continuing to use the services after changes take
          effect means you accept them.
        </p>
      </Section>

      <Section n={13} title="Governing law">
        <p>
          These terms are governed by the laws of {COMPANY.jurisdiction}, and the
          courts of {COMPANY.jurisdiction} have exclusive jurisdiction over any
          dispute, subject to any mandatory consumer rights you have in your
          place of residence.
        </p>
      </Section>

      <Section n={14} title="Contact">
        <p>
          Questions about these terms? Email{" "}
          <a href={`mailto:${COMPANY.email.legal}`} className="text-brand-300 hover:underline">
            {COMPANY.email.legal}
          </a>
          .
        </p>
      </Section>
    </LegalPage>
  );
}
